### PR TITLE
Update Anubis & Dust II

### PR DESCRIPTION
**Pull request by oneiricbotcelot**
Valve has recently updated Anubis and Dust II, so I uploaded the current radar images.

### CODE REVIEW

**Review by NikoGrano — CHANGES_REQUESTED** [review]
Please also update `data.json`.

**Comment by oneiricbotcelot** [comment]
> Please also update `data.json`.

There is nothing to update, file names and paths stayed the same.

**Comment by NikoGrano** [comment]
Based on https://github.com/GameTactic/Maps/pull/2/files you deleted 2 images. Is this branch missing some changes? 🦺

**Comment by oneiricbotcelot** [comment]
As you can see [here](https://github.com/GameTactic/Maps/tree/maps-update/csgo/resources), they are still there. They were just replaced by two files with the same file name.

**Comment by NikoGrano** [comment]
Yeh, sorry my bad! Can you also update "Chlorine"?

**Comment by oneiricbotcelot** [comment]
Acutally that was my fault in the update comment. Chlorine was updated on the date of the initial commit and I have actually pushed the recent version in my first commit. Just wasn't sure anymore, so I did it again. Github recognised that there were no differences between the files and so it did nothing on that regard.

**Review by NikoGrano — APPROVED** [review]
LGTM

**Pull request merged**
